typography_spectrum: 0.356851021759212
color:
  brandStrength: 0.9500976181589067
  lightness: 0.19383918587118387
  saturation: 0.05951385502703488
  rhythmicContrast: 0.005600948818027973
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.32020700024440885
name: ':: alphahippie ::'
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/myles.blackwood'
    type: external
title: think about it
description: we just think it's funny
